.PHONY: all
all: autosuggestions syntax-highlighting tab-completions

autosuggestions:
	git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/zsh/plugins/zsh-autosuggestions

syntax-highlighting:
	git clone https://github.com/zdharma/fast-syntax-highlighting ~/.config/zsh/plugins/fast-syntax-highlighting

tab-completions:
	git clone https://github.com/zsh-users/zsh-completions ~/.config/zsh/plugins/zsh-completions